version: '3.9'

services:
  web:
    container_name: web
    image: lusieda/django-app:latest
    env_file:
      - /home/ec2-user/app/.env
    expose:
      - "8000"

    command: bash -c "poetry run gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    restart: always
    networks:
      - ws
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - ./static:/app/static
      - /home/ec2-user/app/media:/app/media

  nginx:
    container_name: NGINX
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /home/ec2-user/app/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /home/ec2-user/app/static:/app/static
      - /home/ec2-user/app/media:/app/media
    depends_on:
      - web
    restart: always
    networks:
      - ws