version: '3.9'

services:
  #배포시 지워요
  db:
    container_name: db
    image: postgres:17
    restart: always
    env_file:
      - ./.env
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ws
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    command: sh /app/scripts/run.sh
    env_file:
      - ./.env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.prod
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    networks:
      - ws

volumes:
  postgres_data:

networks:
  ws:
    driver: bridge

