version: '3.9'

services:
  web:
    container_name: web
    image: lusieda/django-app:latest
    env_file:
      - /home/ec2-user/app/.env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.prod
    ports:
      - "8000:8000"

    command: >
      bash -c "
      python manage.py migrate --fake-initial &&
      gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3
      "
    restart: on-failure
    networks:
      - ws
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s
volumes: {}

networks:
  ws:
    driver: bridge