name: Deploy to EC2

on:
  workflow_run:
    workflows: ["Build Docker Image"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    env:
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USER: ${{ secrets.EC2_USER }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      EC2_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}

      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
    steps:
      - name: Prepare SSH key

        run: |
          mkdir -p ~/.ssh
          echo "$EC2_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts

      - name: Deploy to EC2

        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $EC2_USER@$EC2_HOST << EOF
          cd /home/ec2-user/app
          WEB_CONTAINER=web
          IMAGE_NAME=$DOCKER_USERNAME/django-app:latest
          
          # 기존 컨테이너 중지/삭제
          docker stop $WEB_CONTAINER || true
          docker rm $WEB_CONTAINER || true

            # 최신 이미지 pull
          docker pull $IMAGE_NAME
          
          # EC2에 .env 파일 자동 생성
            
          cat <<EOT > .env
          POSTGRES_DB=${POSTGRES_DB}
          POSTGRES_USER=${POSTGRES_USER}
          POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          DB_HOST=${DB_HOST}
          DB_PORT=${DB_PORT}
          DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
          ALLOWED_HOSTS=${ALLOWED_HOSTS}
          EOT


          # 컨테이너 실행
          docker run -d --name $WEB_CONTAINER -p 8000:8000 --env-file ./.env $IMAGE_NAME

          # Django migration & static collect
          docker exec $WEB_CONTAINER poetry run python manage.py migrate
          docker exec $WEB_CONTAINER poetry run python manage.py collectstatic --noinput

          # 불필요한 이미지 정리
          docker image prune -af

          # 확인
          docker ps
          EOF
